// Generated by CoffeeScript 1.6.2
var Contact;

jQuery.fn.contact = function(options) {
  return new Contact(options, this);
};

Contact = (function() {
  Contact.prototype.label = 'Контакт';

  Contact.prototype.ctl = ['^', 'X'];

  Contact.prototype.size = [320, 320];

  Contact.prototype.control = [320, 32];

  function Contact(options, elem) {
    var _ref, _ref1, _ref2, _ref3, _ref4;

    this.options = options;
    this.elem = elem;
    if ((_ref = this.options) != null ? _ref.position : void 0) {
      $(this.elem).addClass('conntact-' + ((_ref1 = this.options) != null ? _ref1.position : void 0));
    }
    if ((_ref2 = this.options) != null ? _ref2.label : void 0) {
      this.label = this.options.label;
    }
    if ((_ref3 = this.options) != null ? _ref3.size : void 0) {
      this.size = this.options.size;
    }
    if ((_ref4 = this.options) != null ? _ref4.url : void 0) {
      this.url = this.options.url;
    }
    $(this.elem).css('width', this.control[0]);
    $(this.elem).css('height', this.control[1]);
    $(this.elem).html(["<div id='control'>", "<span id='label'>" + this.label + "</span>", "<span id='ctl'>" + this.ctl[0] + "</span>", '</div>', "<div id='workspace'></div>"].join(''));
    $(this.elem).find('#control').css('height', this.control[1]);
    this.events();
  }

  Contact.prototype.display = function() {
    var self;

    self = this;
    console.log(this.url);
    $(this.elem).attr('height', this.size[1] + 32);
    return $(this.elem).find('#workspace').html(['<iframe width=100% height="' + this.size[1] + '" frameborder=0 src="' + this.url + '">', '</iframe>'].join(''));
  };

  Contact.prototype.clean = function() {
    return $(this.elem).html('');
  };

  Contact.prototype.events = function() {
    var self;

    self = this;
    return $(this.elem).find('#control').on('click', function(e) {
      if (!self.open) {
        $(self.elem).find('#ctl').html(self.ctl[1]);
        return $(self.elem).animate({
          height: self.size[1] + self.control[1]
        }, 400, function() {
          self.open = true;
          return self.display();
        });
      } else {
        $(self.elem).find('#ctl').html(self.ctl[0]);
        return $(self.elem).animate({
          height: '32'
        }, 400, function() {
          self.open = false;
          return self.clean();
        });
      }
    });
  };

  return Contact;

})();
