// Generated by CoffeeScript 1.4.0
(function() {
  var Popup;

  jQuery.fn.popup = function(options) {
    return new Popup(options, this);
  };

  Popup = (function() {

    Popup.prototype.label = 'Popup';

    Popup.prototype.checkStatus = false;

    Popup.prototype.status = true;

    Popup.prototype.open = false;

    function Popup(options, elem) {
      var _ref, _ref1, _ref2, _ref3;
      this.options = options;
      this.elem = elem;
      $(this.elem).hide();
      if ((_ref = this.options) != null ? _ref.position : void 0) {
        this.position = this.options.position;
      }
      if ((_ref1 = this.options) != null ? _ref1.label : void 0) {
        this.label = this.options.label;
      }
      if ((_ref2 = this.options) != null ? _ref2.url : void 0) {
        this.url = this.options.url;
      }
      if ((_ref3 = this.options) != null ? _ref3.checkStatus : void 0) {
        this.checkStatus = this.options.checkStatus;
      }
      if (this.checkStatus) {
        this.checkOnLine();
      } else {
        this.display();
      }
    }

    Popup.prototype.display = function() {
      $(this.elem).hide();
      $(this.elem).html(["<h4 class='btn'>" + this.label, "<span></span>", "</h4>", '<iframe frameborder=0 src="' + this.url + '"></iframe>'].join(''));
      $(this.elem).addClass('popup-' + this.position);
      $(this.elem).addClass('popupClose');
      $(this.elem).show();
      return this.events();
    };

    Popup.prototype.checkOnLine = function() {
      var img, self;
      self = this;
      img = document.body.appendChild(document.createElement("img"));
      img.onload = function() {
        self.status = true;
        return self.display();
      };
      img.onerror = function() {
        self.status = false;
        return $(self.elem).hide();
      };
      return img.src = self.url + "/status.gif";
    };

    Popup.prototype.events = function() {
      var duration, h4, iframe, self, span;
      self = this;
      h4 = $(this.elem).find('h4');
      span = $(this.elem).find('h4 span');
      iframe = $(this.elem).find('iframe');
      duration = 400;
      return h4.on('click', function(e) {
        if (!self.open) {
          $(self.elem).removeClass('popupClose');
          $(self.elem).addClass('popupOpen');
          return self.open = true;
        } else {
          $(self.elem).removeClass('popupOpen');
          $(self.elem).addClass('popupClose');
          return self.open = false;
        }
      });
    };

    return Popup;

  })();

}).call(this);
