// Generated by CoffeeScript 1.4.0
(function() {
  var Popup;

  jQuery.fn.popup = function(options) {
    return new Popup(options, this);
  };

  Popup = (function() {

    Popup.prototype.label = 'Popup';

    Popup.prototype.ctl = ['^', 'X'];

    Popup.prototype.size = [320, 32, 320];

    Popup.prototype.checkStatus = false;

    Popup.prototype.status = true;

    Popup.prototype.open = false;

    function Popup(options, elem) {
      var _ref, _ref1, _ref2, _ref3, _ref4;
      this.options = options;
      this.elem = elem;
      if (((_ref = this.options) != null ? _ref.position : void 0) === 'right') {
        this;

      }
      if ((_ref1 = this.options) != null ? _ref1.label : void 0) {
        this.label = this.options.label;
      }
      if ((_ref2 = this.options) != null ? _ref2.size : void 0) {
        this.size = this.options.size;
      }
      if ((_ref3 = this.options) != null ? _ref3.url : void 0) {
        this.url = this.options.url;
      }
      if ((_ref4 = this.options) != null ? _ref4.checkStatus : void 0) {
        this.checkStatus = this.options.checkStatus;
      }
      if (this.checkStatus) {
        this.checkOnLine();
      } else {
        this.display();
      }
    }

    Popup.prototype.display = function() {
      $(this.elem).html(["<h4>" + this.label, "<span class='hide'></span>", "</h4>", "<div id='workspace'>", '<iframe frameborder=0 src="' + this.url + '">', '</iframe>', "</div>"].join(''));
      $(this.elem).addClass('rotate');
      return this.events();
    };

    Popup.prototype.checkOnLine = function() {
      var img, self;
      self = this;
      img = document.body.appendChild(document.createElement("img"));
      img.onload = function() {
        self.status = true;
        return self.displayControl();
      };
      img.onerror = function() {
        self.status = false;
        return $(this.elem).hide();
      };
      return img.src = self.url + "/status.gif";
    };

    Popup.prototype.events = function() {
      var h4, self, span;
      self = this;
      h4 = $(this.elem).find('h4');
      span = $(this.elem).find('h4 span');
      return h4.on('click', function(e) {
        if ($(self.elem).hasClass('rotate')) {
          $(self.elem).toggle(200, function() {
            $(self.elem).removeClass('rotate');
            $(self.elem).addClass('normal');
            return $(self.elem).toggle(200, function() {
              return span.show();
            });
          });
        }
        if ($(self.elem).hasClass('normal')) {
          return $(self.elem).toggle(200, function() {
            $(self.elem).removeClass('normal');
            $(self.elem).addClass('rotate');
            return $(self.elem).toggle(200, function() {
              return span.hide();
            });
          });
        }
      });
    };

    return Popup;

  })();

}).call(this);
